config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'pages/home'
  get 'pages/map'
  root to: 'pages#home'
  #root to: 'categories#index'
  resources :events, controller: :events, only: [:index, :show]
  resources :categories, controller: :categories, only: [:index, :show]
  resources :users, conroller: :users, only: :show
  resources :bookmarks, controller: :bookmarks, only: [:index, :create, :destroy]

  # Service Worker Routes
  get '/service-worker.js' => "service_worker#service_worker"
  get '/manifest.json' => "service_worker#manifest"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/bookmark_event.rb
class BookmarkEvent < ApplicationRecord
  belongs_to :event
  belongs_to :bookmark
end

app/models/bookmark_user.rb
class BookmarkUser < ApplicationRecord
  belongs_to :user
  belongs_to :bookmark
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :category
  has_many :bookmarks, through: :bookmark_events

  geocoded_by :address
  searchkick
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookmarks, through: :bookmark_users
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :create, :delete]
  before_action :set_current_user, only: [:indes, :delete]

  def index
    @bookmarks = policy_scope(Bookmark)
    @bookmarks = @bookmarks.where(user: current_user)
  end

  def create
    @bookmark = Bookmark.new(user: current_user, event_id: params[:format].to_i)
    @bookmark.save
    authorize @bookmark
    redirect_to @bookmark.event
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    authorize @bookmark
    redirect_to @bookmark.event
  end

  private

  def set_current_user
    @user = current_user
    authorize @user
  end

  def bookmark_params
    params.require(:bookmark).permit(:user, :event)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_category, only: [:show]

  def index
    @categories = policy_scope(Category)
  end

  def show
    if @category.id != "1"
      @events = Event.where(category: @category)
    else
      @events = Event.all
    end

    # @events.sort(:date).each do |event|
    #= render partial: 'events/event_card', locals: { event: event }
    # end

    #if params[:query] != ""
    #  @events = @events.search params[:query]
    #end
    if params[:date_range] != ""
      date_range_array = params[:date_range].split(" to ")
      start_date = Date.parse date_range_array.first
      end_date = Date.parse date_range_array.last
      date_range_array = (start_date..end_date).to_a
      if params[:query] != ""
        @events = @events.search(params[:query], where: { date: date_range_array })
      else
        @events = @events.search(where: { date: date_range_array })
      end
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
    authorize @category
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_event, only: [:show]
  require 'scraping/event_scraper'

  def index
    save_user_location
    Event.reindex
    @events = policy_scope(Event)
    #@events = Event.search(params[:query]) if params[:query]
    #@events.each { |event| get_distance(event) if event.latitude != nil }
    set_bookmarks
  end

  def show
    set_bookmarks
  end

  private

  def set_event
    @event = Event.find(params[:id])
    authorize @event
  end

  def save_user_location
    current_location = cookies[:cl]
    unless current_location.nil?
      @latitude = current_location.split('&')[0].to_f
      @longitude = current_location.split('&')[1].to_f
    end
  end

  def get_distance(event)
    url = "https://maps.googleapis.com/maps/api/directions/json?origin=#{@latitude},#{@longitude}&destination=#{event.latitude},#{event.longitude}&key=#{ENV['GOOGLE_API_KEY_DIRECTIONS']}"
    http_call = open(url).read
    response = JSON.parse(http_call, {symbolize_name: true})
    @distance = response["routes"][0]["legs"][0]["distance"]["text"]
  end

  def set_bookmarks
    @bookmarks = policy_scope(Bookmark)
    @bookmarks = @bookmarks.where(user: current_user)
    #authorize @bookmark
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :map]

  def home
    @events = policy_scope(Event)
  end

  def map
    @events = policy_scope(Event)
    @events = Event.where(date: Date.today).geocoded

    @markers = @events.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { event: event })
      }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :set_current_user, only: [:show, :edit, :update]

  def show
  end

  private

  def set_current_user
    @user = current_user
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def root_path?
    request.path == "/" ? true : false
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/service_worker_helper.rb
module ServiceWorkerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oldenburg Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- Lighthouse Details -->
    <link rel="manifest" href="/manifest.json">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#C50001"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js" %>
    <%= javascript_include_tag "https://unpkg.com/swiper/js/swiper.js" %>
    <%= javascript_include_tag "https://unpkg.com/swiper/js/swiper.min.js" %>
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/pages/_info_window.html.erb
<%= link_to event_path(event) do  %>
  <div>
    <%= image_tag event.image, height: 100, width: 200, crop: :fill, alt: "event_image" %>
    <br>
    <strong><%= event.name %></strong>
  </div>
  <p><%= event.location %></p>
<% end %>

app/views/pages/home.html.erb
<!--<div class="app-title">
  <div>Veranstaltungen</div>
  <div>Oldenburg</div>
</div>-->

<div class="container">
  <% if @events.where(date: Date.today) != [] %>
    <h4>Heute</h4>
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <% @events.where(date: Date.today).order(:date).each do |event| %>
          <div class="swiper-slide">
            <%= render partial: 'events/event_card', locals: { event: event } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if @events.where(date: (Date.today + 1))  != [] %>
    <h4>Morgen</h4>
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <% @events.where(date: (Date.today + 1)).order(:date).each do |event| %>
          <div class="swiper-slide">
            <%= render partial: 'events/event_card', locals: { event: event } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>


  <% if @events.where(date: (Date.today + 2)..(Date.today + 8)) != [] %>
    <% start_date = Date.today + 1 %>
    <% div_open = false %>

    <% @events.where(date: (Date.today + 2)..(Date.today + 8)).order(:date).each do |event| %>
      <% if event.date != start_date %>
        <% start_date += 1 until start_date == event.date %>
        <% if div_open %>
          </div>
          </div>
        <% end %>
        <h4><%= l(start_date, format: '%A, %d.%m.%Y') %></h4>
        <div class="swiper-container">
        <div class="swiper-wrapper">
        <% div_open = true %>
      <% end %>
        <div class="swiper-slide">
          <%= render partial: 'events/event_card', locals: { event: event } %>
        </div>
      <% if @events.where(date: (Date.today + 2)..(Date.today + 8)).order(:date).last == event %>
        </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/pages/map.html.erb
<div
  id="map"
  style="width: 100%; height: 100vh;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-element">
    <%= link_to pages_home_path, class: "footer-link" do %>
      <i class="fas fa-home"></i>
      <div class="footer-text">HOME</div>
    <% end %>
  </div>
  <div class="footer-element">
    <%= link_to categories_path, class: "footer-link" do %>
      <i class="fas fa-calendar-alt"></i>
      <div class="footer-text">KATEGORIEN</div>
    <% end %>
  </div>
  <div class="footer-element">
    <%= link_to pages_map_path, class: "footer-link" do %>
      <i class="fas fa-map-marker-alt"></i>
      <div class="footer-text">KARTE</div>
    <% end %>
  </div>
  <div class="footer-element">
    <% if user_signed_in? %>
      <%= link_to bookmarks_path, class: "footer-link" do %>
        <i class="fas fa-bookmark"></i>
        <div class="footer-text">MERKLISTE</div>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "footer-link" do %>
        <i class="fas fa-bookmark"></i>
        <div class="footer-text">MERKLISTE</div>
      <% end %>
    <% end %>
  </div>
  <div class="footer-element">
    <% if user_signed_in? %>
      <%= link_to user_path(current_user), class: "footer-link" do %>
        <i class="fas fa-user"></i>
        <div class="footer-text">PROFIL</div>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "footer-link" do %>
        <i class="fas fa-user"></i>
        <div class="footer-text">PROFIL</div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to :back, class: "navbar-brand" do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>