config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'pages/home'
  get 'pages/map'
  root to: 'pages#home'
  #root to: 'categories#index'
  resources :events, controller: :events, only: [:index, :show]
  resources :categories, controller: :categories, only: [:index, :show]
  resources :users, conroller: :users, only: :show
  resources :bookmarks, controller: :bookmarks, only: [:index, :create, :destroy]

  # Service Worker Routes
  get '/service-worker.js' => "service_worker#service_worker"
  get '/manifest.json' => "service_worker#manifest"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/bookmark_event.rb
class BookmarkEvent < ApplicationRecord
  belongs_to :event
  belongs_to :bookmark
end

app/models/bookmark_user.rb
class BookmarkUser < ApplicationRecord
  belongs_to :user
  belongs_to :bookmark
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :category
  has_many :bookmarks, through: :bookmark_events

  geocoded_by :address
  searchkick
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookmarks, through: :bookmark_users
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :create, :delete]
  before_action :set_current_user, only: [:indes, :delete]

  def index
    @bookmarks = policy_scope(Bookmark)
    @bookmarks = @bookmarks.where(user: current_user)
  end

  def create
    @bookmark = Bookmark.new(user: current_user, event_id: params[:format].to_i)
    @bookmark.save
    authorize @bookmark
    redirect_to @bookmark.event
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    authorize @bookmark
    redirect_to @bookmark.event
  end

  private

  def set_current_user
    @user = current_user
    authorize @user
  end

  def bookmark_params
    params.require(:bookmark).permit(:user, :event)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_category, only: [:show]

  def index
    @categories = policy_scope(Category)
  end

  def show
    if @category.id != "1"
      @events = Event.where(category: @category)
    else
      @events = Event.all
    end

    # @events.sort(:date).each do |event|
    #= render partial: 'events/event_card', locals: { event: event }
    # end

    #if params[:query] != ""
    #  @events = @events.search params[:query]
    #end
    if params[:date_range] != ""
      date_range_array = params[:date_range].split(" to ")
      start_date = Date.parse date_range_array.first
      end_date = Date.parse date_range_array.last
      date_range_array = (start_date..end_date).to_a
      if params[:query] != ""
        @events = @events.search(params[:query], where: { date: date_range_array })
      else
        @events = @events.search(where: { date: date_range_array })
      end
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
    authorize @category
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_event, only: [:show]
  require 'scraping/event_scraper'

  def index
    save_user_location
    Event.reindex
    @events = policy_scope(Event)
    #@events = Event.search(params[:query]) if params[:query]
    #@events.each { |event| get_distance(event) if event.latitude != nil }
    set_bookmarks
  end

  def show
    set_bookmarks
  end

  private

  def set_event
    @event = Event.find(params[:id])
    authorize @event
  end

  def save_user_location
    current_location = cookies[:cl]
    unless current_location.nil?
      @latitude = current_location.split('&')[0].to_f
      @longitude = current_location.split('&')[1].to_f
    end
  end

  def get_distance(event)
    url = "https://maps.googleapis.com/maps/api/directions/json?origin=#{@latitude},#{@longitude}&destination=#{event.latitude},#{event.longitude}&key=#{ENV['GOOGLE_API_KEY_DIRECTIONS']}"
    http_call = open(url).read
    response = JSON.parse(http_call, {symbolize_name: true})
    @distance = response["routes"][0]["legs"][0]["distance"]["text"]
  end

  def set_bookmarks
    @bookmarks = policy_scope(Bookmark)
    @bookmarks = @bookmarks.where(user: current_user)
    #authorize @bookmark
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :map]

  def home
    @events = policy_scope(Event)
  end

  def map
    @events = policy_scope(Event)
    @events = Event.where(date: Date.today).geocoded

    @markers = @events.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { event: event })
      }
    end
  end
end

app/controllers/service_worker_controller.rb
class ServiceWorkerController < ApplicationController
  protect_from_forgery except: :service_worker
  skip_before_action :authenticate_user!, only: [:service_worker, :manifest]
  def service_worker
  end

  def manifest
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :set_current_user, only: [:show, :edit, :update]

  def show
  end

  private

  def set_current_user
    @user = current_user
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def root_path?
    request.path == "/" ? true : false
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/service_worker_helper.rb
module ServiceWorkerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/delete.html.erb
<h1>Bookmarks#delete</h1>
<p>Find me in app/views/bookmarks/delete.html.erb</p>

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>

<% @bookmarks.each do |bookmark| %>
  <%= bookmark.event.name %>
<% end %>

app/views/categories/index.html.erb
<div class="navbar">
  <div></div>
  <h3> Kategorien </h3>
  <div></div>
</div>

<div class="index-container">
  <div>
    <%= form_tag events_path, method: :get, class: "search-bar" do %>
      <%= text_field_tag :query,
      params[:query],
      class: "input-field"
      #,placeholder: ""
      %>
      <%= button_tag(type: "submit", class: "btn btn-search") do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>
  </div>

  <% @categories.each do |category| %>
    <%= link_to category_path(category) do %>
    <% if category.image != nil %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path category.image %>)">
        <%= category.name %>
      </div>
    <% end %>
    <% end %>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="navbar">
  <%= link_to categories_path, class: "navbar-brand" do %>
    <div class="back"><i class="fas fa-chevron-left"></i></div>
  <% end %>
  <div><h3><%= @category.name %></h3></div>
  <div></div>
</div>

<div class="index-container">
  <h5 id="location"></h5>

  <div>
    <%= form_tag category_path, method: :get, class: "search-bar" do %>
      <%= text_field_tag :query,
      params[:query],
      class: "input-field"
      #,placeholder: ""
      %>
      <%= text_field_tag :date_range, params[:date_range], class: "datepicker" %>
      <%= button_tag(type: "submit", class: "btn btn-search") do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>
  </div>

  <% @events.each do |event| %>
    <%= render partial: 'events/event_card', locals: { event: event } %>
  <% end %>

  <%# if @events.where(date: Date.today) != [] %>
  <!--  <h4>Heute</h4>
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <%# @events.where(date: Date.today).order(:date).each do |event| %>
          <div class="swiper-slide">
            <%#= render partial: 'events/event_card', locals: { event: event } %>
          </div>
        <%# end %>
      </div>
    </div>
  <%# end %>

  <%# if @events.where(date: (Date.today + 1))  != [] %>
    <h4>Morgen</h4>
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <%# @events.where(date: (Date.today + 1)).order(:date).each do |event| %>
          <div class="swiper-slide">
            <%#= render partial: 'events/event_card', locals: { event: event } %>
          </div>
        <%# end %>
      </div>
    </div>
  <%# end %>

  <%# if @events.where("date > ?", Date.today + 1) != [] %>
    <%# end_date = Date.today + 1 %>
    <%# div_open = false %>

    <%# @events.where("date > ?", Date.today + 1).order(:date).each do |event| %>
      <%# if event.date > end_date %>
        <%# end_date += 8 until ((end_date - 7)..(end_date)).include? event.date %>
        <%# if div_open %>
          </div>
          </div>
        <%# end %>
        <h4><%#= (end_date - 7).strftime('%d.%m.%Y') + " - " + end_date.strftime('%d.%m.%Y') %></h4>
        <div class="swiper-container">
        <div class="swiper-wrapper">
        <%# div_open = true %>
      <%# end %>
        <div class="swiper-slide">
          <%#= render partial: 'events/event_card', locals: { event: event } %>
        </div>
      <%# if @events.where("date > ?",(Date.today + 1)).order(:date).last == event %>
        </div>
        </div>
      <%# end %>
    <%# end %>
  <%# end %>
-->
</div>

app/views/events/_event_card.html.erb
<%= link_to event_path(event), class: 'event-card' do %>
  <div class="card-event">
    <div class="card-img">

      <%= image_tag(event.image) if event.image %>
    </div>
    <div class="card-info">
      <strong><%= truncate(event.name, length: 65) if event.name %></strong><br>
      <%= event.location if event.location %><br>
      <%= event.date.strftime('%d.%m.%Y') if event.date %> <i class="far fa-clock"></i> <%= event.time.strftime('%H:%M') if event.time %>
      <div class="bookmark">
        <%#= social_share_button_tag("My App", :allow_sites => %w(whatsapp_app)) %>
        <i class="fas fa-paper-plane"></i>
        <i class="far fa-bookmark"></i>
      <!-- if gemerkt
      <i class="fas fa-bookmark"></i> -->
      </div>
      <!-- <i class="fas fa-map-marker-alt ml-2"></i> --> <%#= @distance %>
    </div>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="navbar">
  <%= link_to categories_path, class: "navbar-brand" do %>
    <div class="back"><i class="fas fa-chevron-left"></i></div>
  <% end %>
  <div><h3>
    <% if params[:format] %>
      <%= Category.find(params[:format]).name %>
    <% else %>
      Alle Veranstaltungen
    <% end %>
    </h3></div>
  <div></div>
</div>

<div class="index-container">
  <h5 id="location"></h5>

  <% if params[:format] != "1" %>
    <% @events = @events.where(category_id: params[:format]) %>
  <% end %>
  <% if params[:query] != "" %>
    <% @events = Event.search(params[:query])#.where(category: @category) %>
  <% else %>
    <% @events = Event.all %>
  <% end %>

  <%# @events.sort(:date).each do |event| %>
    <%#= render partial: 'events/event_card', locals: { event: event } %>
  <%# end %>

  <div>
    <%= form_tag events_path, method: :get, class: "search-bar" do %>
      <%= text_field_tag :query,
      params[:query],
      class: "input-field"
      #,placeholder: ""
      %>
      <%= button_tag(type: "submit", class: "btn btn-search") do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>
  </div>

  <% @events.each do |event| %>
    <%= render partial: 'events/event_card', locals: { event: event } %>
  <% end %>

  <%# if @events.where(date: Date.today) != [] %>
  <!--  <h4>Heute</h4>
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <%# @events.where(date: Date.today).order(:date).each do |event| %>
          <div class="swiper-slide">
            <%#= render partial: 'events/event_card', locals: { event: event } %>
          </div>
        <%# end %>
      </div>
    </div>
  <%# end %>

  <%# if @events.where(date: (Date.today + 1))  != [] %>
    <h4>Morgen</h4>
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <%# @events.where(date: (Date.today + 1)).order(:date).each do |event| %>
          <div class="swiper-slide">
            <%#= render partial: 'events/event_card', locals: { event: event } %>
          </div>
        <%# end %>
      </div>
    </div>
  <%# end %>

  <%# if @events.where("date > ?", Date.today + 1) != [] %>
    <%# end_date = Date.today + 1 %>
    <%# div_open = false %>

    <%# @events.where("date > ?", Date.today + 1).order(:date).each do |event| %>
      <%# if event.date > end_date %>
        <%# end_date += 8 until ((end_date - 7)..(end_date)).include? event.date %>
        <%# if div_open %>
          </div>
          </div>
        <%# end %>
        <h4><%#= (end_date - 7).strftime('%d.%m.%Y') + " - " + end_date.strftime('%d.%m.%Y') %></h4>
        <div class="swiper-container">
        <div class="swiper-wrapper">
        <%# div_open = true %>
      <%# end %>
        <div class="swiper-slide">
          <%#= render partial: 'events/event_card', locals: { event: event } %>
        </div>
      <%# if @events.where("date > ?",(Date.today + 1)).order(:date).last == event %>
        </div>
        </div>
      <%# end %>
    <%# end %>
  <%# end %>
-->
</div>

app/views/events/show.html.erb
<div class="navbar">
  <%= link_to :back, class: "navbar-brand" do %>
    <div class="back"><i class="fas fa-chevron-left"></i></div>
  <% end %>
  <div><h3><%#= @event.name %></h3></div>
  <div></div>
</div>

<div class="event">
  <%= image_tag(@event.image) if @event.image != nil %>
  <div class="show-container">
    <h1><%= @event.name %></h1>
    <%= @event.location %>
    <br>
    <%= @event.date.strftime('%d.%m.%Y') %> <i class="far fa-clock"></i> <%= @event.time.strftime('%H:%M') %>
    <br><br>
    <%= @event.description %>
    <br>
    <% if request.env['HTTP_USER_AGENT'].downcase.match(/android/) %>
      <%= link_to "http://maps.apple.com/?q=#{@event.address}" do %>
          <i class="fas fa-map-marked-alt"></i>
      <% end %>
    <% elsif request.env['HTTP_USER_AGENT'].downcase.match(/iphone/) %>
      <%= link_to "comgooglemaps://?q=#{@event.address}" do %>
        <i class="fas fa-map-marked-alt"></i>
      <% end %>
    <% else %>
      <%= link_to "http://maps.apple.com/?q=#{@event.address}", target: :_blank do %>
          <i class="fas fa-map-marked-alt"></i>
      <% end %>

      <% if current_user %>
        <% if @bookmarks.where(event: @event.id) != [] %>
          <% @bookmark_id = @bookmarks.where(event: @event.id).first.id %>
          <%= link_to bookmark_path(@bookmark_id), method: :delete do %>
            <i class="fas fa-bookmark"></i>
          <% end %>
        <% else %>
          <%= link_to bookmarks_path(@event), method: :post do %>
            <i class="far fa-bookmark"></i>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <i class="far fa-bookmark"></i>
        <% end %>
      <% end %>

      <button type="button" data-toggle="modal" data-target=".bd-example-modal-sm"><i class="fas fa-paper-plane"></i></button>
      <div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <%= social_share_button_tag("My App", :allow_sites => %w(whatsapp_app facebook)) %>
          </div>
        </div>
      </div>


      <% if @event.ticket %>
        <%= link_to @event.ticket do %>
          <button>Ticket</button>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/service_worker/manifest.json.erb
{
  "short_name": "Oldenburg Veranstaltungen",
  "name": "Alle Veranstaltungen in Oldenburg an einem Ort",
  "icons": [
    {
      "src": "<%= asset_path('icon_192.png') %>",
      "type": "image/png",
      "sizes": "192x192"
    },
    {
      "src": "<%= asset_path('icon_512.png') %>",
      "type": "image/png",
      "sizes": "512x512"
    }
  ],
  "start_url": "<%= root_path %>",
  "background_color": "#fff",
  "display": "standalone",
  "scope": "<%= root_path %>",
  "theme_color": "#000"
}

app/views/users/show.html.erb
<h1>Users#show</h1>

<% if user_signed_in? %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  <%= @user.email %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
<% end %>